// <auto-generated />
namespace MCR_EMApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class metermodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(metermodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201811290619246_metermodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
